line-length = 100

[lint]
select = ["ALL"]
ignore = [
    "COM812", # Trailing comma missing
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "D413", # Missing blank line after last section
    "EM101", # Exception must not use a string literal, assign to variable first
    "EM102", # Exception must not use an f-string literal, assign to variable first
    "TRY003", # Avoid specifying long messages outside the exception class
]

[lint.pylint]
max-args = 10

[lint.per-file-ignores]
"tests/*" = ["D103", "INP001", "S101"]
